### PR TITLE
Subway system completed

### PR DESCRIPTION
**Pull request by syvanen**
- Added all the subway entrances (even ones that aren't shown on in game map)
- Explored to stations to find out their names
- Activated the Subway Entrance map filter
- Small fixes to locations and descriptions

### CODE REVIEW

**Comment by FyerPower** [comment]
Wonder why all the commits were made twice with the same changes. _shrug_

Very nice work!

Thanks.

**Comment by gamegenius86** [comment]
What is your reddit username?  (I dont see any PMs based on your username here, however i could be blind)

**Comment by syvanen** [comment]
I tried out the Github desktop app on OS X and I think it somehow weirdly pulled/rebased the repo. so that's why they were duplicates (not even sure how it's even possible to have them twice)

**Comment by FyerPower** [comment]
Gotcha!  All is good though.  Just thought it was a little weird as they had different commit numbers and the same changes.  Btw: Sent you a message on reddit with discord info, gonna be using that for chatting (Primarily text)

**Pull request merged**
